language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
  - COVERALLS_REPO_TOKEN=TZ1nqgSfZtR97R622NZGTGBNobvEqLrQo coveralls